### PR TITLE
server and mempool

### PR DESCRIPTION
**Pull request by oleggolev**

### CODE REVIEW

**Comment by moinmir** [comment]
> 

lgtm

**Comment by moinmir** [comment]
> 

where's ur comment

**Comment by moinmir** [comment]
also what is this abomination python code inside a rust project

**Comment by oleggolev** [comment]
> also what is this abomination python code inside a rust project

this was all your fault

**Comment by moinmir** [comment]
wait i just realized

**Comment by moinmir** [comment]
this is a project

**Comment by oleggolev** [comment]
this is indeed one of the projects of all time

**Pull request merged**
